"""Export commands — dump project data to Markdown or CSV."""

from __future__ import annotations

import csv
import io
from datetime import datetime, timezone
from pathlib import Path
from typing import Optional

import click

from ..db import Database
from ..models import Status
from ..ui import print_error, print_success, console


@click.group("export")
def export_cmd():
    """Export project data to files."""


# ── Markdown export ───────────────────────────────────────────────────────────

def _build_markdown(db: Database, project_id: int) -> str:
    """Build a full Markdown document for a project."""
    project = db.get_project(project_id)
    if not project:
        return ""

    stats = db.project_stats(project_id)
    tasks = db.list_tasks(project_id=project_id)
    sprints = db.list_sprints(project_id)

    pct = f"{stats.completion_pct:.0f}" if stats else "0"
    done_count = stats.done_tasks if stats else 0
    total_count = stats.total_tasks if stats else 0
    hours = stats.total_hours_logged if stats else 0.0

    lines: list[str] = []

    # Header
    lines.append(f"# {project.name}")
    if project.description:
        lines.append(f"\n> {project.description}")
    lines.append(f"\n**Status:** {project.status.value}  ")
    lines.append(f"**Progress:** {done_count}/{total_count} tasks ({pct}%)  ")
    lines.append(f"**Hours logged:** {hours:.1f}h  ")
    lines.append(f"**Updated:** {project.updated_at.strftime('%Y-%m-%d')}")

    # Sprints
    if sprints:
        lines.append("\n---\n\n## Sprints\n")
        for s in sprints:
            start = s.starts_at.strftime("%Y-%m-%d") if s.starts_at else "—"
            end = s.ends_at.strftime("%Y-%m-%d") if s.ends_at else "—"
            lines.append(f"### {s.name}  `{s.status.value}`")
            if s.goal:
                lines.append(f"\n*Goal: {s.goal}*")
            lines.append(f"\nDates: {start} → {end}")
            sprint_tasks = [t for t in tasks if t.sprint_id == s.id]
            if sprint_tasks:
                lines.append("\n| # | Title | Priority | Status | Est | Act |")
                lines.append("|---|-------|----------|--------|-----|-----|")
                for t in sprint_tasks:
                    est = f"{t.estimate_hours:.1f}h" if t.estimate_hours else "—"
                    act = f"{t.actual_hours:.1f}h" if t.actual_hours else "—"
                    lines.append(
                        f"| {t.id} | {t.title} | {t.priority.value} | {t.status.value} | {est} | {act} |"
                    )
            lines.append("")

    # Tasks by status
    lines.append("\n---\n\n## Tasks\n")

    groups = [
        ("In Progress", [t for t in tasks if t.status == Status.IN_PROGRESS]),
        ("To Do", [t for t in tasks if t.status == Status.TODO]),
        ("Done", [t for t in tasks if t.status == Status.DONE]),
        ("Blocked", [t for t in tasks if t.status == Status.BLOCKED]),
        ("Cancelled", [t for t in tasks if t.status == Status.CANCELLED]),
    ]

    for group_name, group_tasks in groups:
        if not group_tasks:
            continue
        lines.append(f"### {group_name}\n")
        lines.append("| # | Title | Priority | Est | Act |")
        lines.append("|---|-------|----------|-----|-----|")
        for t in group_tasks:
            est = f"{t.estimate_hours:.1f}h" if t.estimate_hours else "—"
            act = f"{t.actual_hours:.1f}h" if t.actual_hours else "—"
            lines.append(f"| {t.id} | {t.title} | {t.priority.value} | {est} | {act} |")
            if t.description:
                lines.append(f"|   | *{t.description}* | | | |")
        lines.append("")

    # Time log
    all_entries = []
    for t in tasks:
        entries = db.list_time_entries(t.id)
        for e in entries:
            all_entries.append((e.logged_at, t.title, e.hours, e.note))

    if all_entries:
        all_entries.sort(key=lambda x: x[0])
        lines.append("\n---\n\n## Time Log\n")
        lines.append("| Date | Task | Hours | Note |")
        lines.append("|------|------|-------|------|")
        for logged_at, title, hrs, note in all_entries:
            lines.append(
                f"| {logged_at.strftime('%Y-%m-%d %H:%M')} | {title} | {hrs:.1f}h | {note or '—'} |"
            )
        lines.append("")

    # Footer
    lines.append(f"\n---\n\n*Generated by Nexus on {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}*")

    return "\n".join(lines) + "\n"


@export_cmd.command("markdown")
@click.argument("project_id", type=int)
@click.option(
    "-o", "--output",
    default=None,
    type=click.Path(),
    help="Output file path. Defaults to <project-slug>.md in current directory.",
)
@click.option("--stdout", is_flag=True, default=False, help="Print to stdout instead of a file.")
@click.pass_obj
def export_markdown(db: Database, project_id: int, output: Optional[str], stdout: bool):
    """Export a project to a Markdown document."""
    project = db.get_project(project_id)
    if not project:
        print_error(f"Project id={project_id} not found.")
        raise SystemExit(1)

    content = _build_markdown(db, project_id)

    if stdout:
        click.echo(content)
        return

    out_path = Path(output) if output else Path(f"{project.slug}.md")
    out_path.write_text(content, encoding="utf-8")
    print_success(f"Exported [bold]{project.name}[/bold] → [cyan]{out_path}[/cyan]  ({len(content):,} bytes)")


# ── CSV export ────────────────────────────────────────────────────────────────

def _build_tasks_csv(db: Database, project_id: int) -> str:
    tasks = db.list_tasks(project_id=project_id)
    sprints = {s.id: s.name for s in db.list_sprints(project_id)}

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow([
        "id", "title", "description", "status", "priority",
        "sprint", "estimate_hours", "actual_hours",
        "created_at", "updated_at", "completed_at",
    ])
    for t in tasks:
        writer.writerow([
            t.id,
            t.title,
            t.description,
            t.status.value,
            t.priority.value,
            sprints.get(t.sprint_id, "") if t.sprint_id else "",
            t.estimate_hours or "",
            t.actual_hours or "",
            t.created_at.strftime("%Y-%m-%d %H:%M"),
            t.updated_at.strftime("%Y-%m-%d %H:%M"),
            t.completed_at.strftime("%Y-%m-%d %H:%M") if t.completed_at else "",
        ])
    return buf.getvalue()


def _build_timelog_csv(db: Database, project_id: int) -> str:
    tasks = db.list_tasks(project_id=project_id)
    task_map = {t.id: t.title for t in tasks}

    rows = []
    for task_id, title in task_map.items():
        for e in db.list_time_entries(task_id):
            rows.append((e.logged_at, task_id, title, e.hours, e.note))

    rows.sort(key=lambda r: r[0])

    buf = io.StringIO()
    writer = csv.writer(buf)
    writer.writerow(["logged_at", "task_id", "task_title", "hours", "note"])
    for logged_at, task_id, title, hours, note in rows:
        writer.writerow([
            logged_at.strftime("%Y-%m-%d %H:%M"),
            task_id,
            title,
            hours,
            note,
        ])
    return buf.getvalue()


@export_cmd.command("csv")
@click.argument("project_id", type=int)
@click.option(
    "--type",
    "csv_type",
    type=click.Choice(["tasks", "timelog"]),
    default="tasks",
    show_default=True,
    help="What to export: task list or time log.",
)
@click.option("-o", "--output", default=None, type=click.Path())
@click.option("--stdout", is_flag=True, default=False)
@click.pass_obj
def export_csv(db: Database, project_id: int, csv_type: str, output: Optional[str], stdout: bool):
    """Export project tasks or time log to CSV."""
    project = db.get_project(project_id)
    if not project:
        print_error(f"Project id={project_id} not found.")
        raise SystemExit(1)

    if csv_type == "tasks":
        content = _build_tasks_csv(db, project_id)
        default_name = f"{project.slug}-tasks.csv"
    else:
        content = _build_timelog_csv(db, project_id)
        default_name = f"{project.slug}-timelog.csv"

    if stdout:
        click.echo(content, nl=False)
        return

    out_path = Path(output) if output else Path(default_name)
    out_path.write_text(content, encoding="utf-8")
    rows = content.count("\n") - 1  # subtract header
    print_success(
        f"Exported [bold]{project.name}[/bold] ({csv_type}) → [cyan]{out_path}[/cyan]  ({rows} rows)"
    )
