"""Tests for the export commands."""

from __future__ import annotations

import csv
import io
from pathlib import Path

import pytest
from click.testing import CliRunner

from nexus.cli import cli
from nexus.commands.export import _build_markdown, _build_tasks_csv, _build_timelog_csv
from nexus.db import Database
from nexus.models import Priority, Status


@pytest.fixture
def runner():
    return CliRunner()


@pytest.fixture
def db_path(tmp_path):
    return str(tmp_path / "test.db")


@pytest.fixture
def populated_db(tmp_path):
    """A database pre-populated with a project, sprint, tasks, and time entries."""
    db = Database(path=tmp_path / "populated.db")
    p = db.create_project("My App", "A great application")
    s = db.create_sprint(p.id, "Sprint 1", goal="Launch v1")
    t1 = db.create_task(p.id, "Write API", priority=Priority.HIGH, estimate_hours=3.0, sprint_id=s.id)
    t2 = db.create_task(p.id, "Build UI", priority=Priority.MEDIUM, estimate_hours=5.0, sprint_id=s.id)
    t3 = db.create_task(p.id, "Write tests", priority=Priority.HIGH, estimate_hours=2.0)
    db.update_task(t1.id, status=Status.DONE)
    db.update_task(t2.id, status=Status.IN_PROGRESS)
    db.log_time(t1.id, 2.5, "backend done")
    db.log_time(t1.id, 0.5, "fixes")
    db.log_time(t2.id, 3.0, "frontend work")
    return db, p, s, [t1, t2, t3]


def invoke(runner, db_path, *args):
    return runner.invoke(cli, ["--db", db_path, *args], catch_exceptions=False)


# ── _build_markdown unit tests ────────────────────────────────────────────────

def test_build_markdown_contains_project_name(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    assert "My App" in md
    assert "A great application" in md


def test_build_markdown_contains_tasks(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    assert "Write API" in md
    assert "Build UI" in md
    assert "Write tests" in md


def test_build_markdown_contains_sprint(populated_db):
    db, p, s, _ = populated_db
    md = _build_markdown(db, p.id)
    assert "Sprint 1" in md
    assert "Launch v1" in md


def test_build_markdown_contains_time_log(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    assert "Time Log" in md
    assert "backend done" in md
    assert "frontend work" in md


def test_build_markdown_missing_project(populated_db):
    db, *_ = populated_db
    md = _build_markdown(db, 9999)
    assert md == ""


def test_build_markdown_has_progress_stats(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    # 1 done out of 3 total = 33%
    assert "1/3" in md or "33%" in md


def test_build_markdown_groups_by_status(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    assert "In Progress" in md
    assert "Done" in md
    assert "To Do" in md


def test_build_markdown_footer_has_timestamp(populated_db):
    db, p, *_ = populated_db
    md = _build_markdown(db, p.id)
    assert "Generated by Nexus" in md


# ── _build_tasks_csv unit tests ───────────────────────────────────────────────

def test_build_tasks_csv_header(populated_db):
    db, p, *_ = populated_db
    content = _build_tasks_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    assert "title" in reader.fieldnames
    assert "status" in reader.fieldnames
    assert "priority" in reader.fieldnames
    assert "estimate_hours" in reader.fieldnames


def test_build_tasks_csv_row_count(populated_db):
    db, p, *_ = populated_db
    content = _build_tasks_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    rows = list(reader)
    assert len(rows) == 3


def test_build_tasks_csv_task_data(populated_db):
    db, p, *_ = populated_db
    content = _build_tasks_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    rows = {r["title"]: r for r in reader}
    assert "Write API" in rows
    assert rows["Write API"]["status"] == "done"
    assert rows["Write API"]["priority"] == "high"
    assert rows["Write API"]["estimate_hours"] == "3.0"


def test_build_tasks_csv_sprint_name(populated_db):
    db, p, s, _ = populated_db
    content = _build_tasks_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    rows = {r["title"]: r for r in reader}
    assert rows["Write API"]["sprint"] == "Sprint 1"
    assert rows["Write tests"]["sprint"] == ""  # not in a sprint


# ── _build_timelog_csv unit tests ─────────────────────────────────────────────

def test_build_timelog_csv_header(populated_db):
    db, p, *_ = populated_db
    content = _build_timelog_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    assert "logged_at" in reader.fieldnames
    assert "task_title" in reader.fieldnames
    assert "hours" in reader.fieldnames
    assert "note" in reader.fieldnames


def test_build_timelog_csv_row_count(populated_db):
    db, p, *_ = populated_db
    content = _build_timelog_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    rows = list(reader)
    assert len(rows) == 3  # 2 on t1, 1 on t2


def test_build_timelog_csv_sorted_by_date(populated_db):
    db, p, *_ = populated_db
    content = _build_timelog_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    dates = [r["logged_at"] for r in reader]
    assert dates == sorted(dates)


def test_build_timelog_csv_notes(populated_db):
    db, p, *_ = populated_db
    content = _build_timelog_csv(db, p.id)
    assert "backend done" in content
    assert "frontend work" in content


def test_build_timelog_csv_empty_project(tmp_path):
    db = Database(path=tmp_path / "empty.db")
    p = db.create_project("Empty")
    content = _build_timelog_csv(db, p.id)
    reader = csv.DictReader(io.StringIO(content))
    assert list(reader) == []


# ── CLI integration tests ─────────────────────────────────────────────────────

def _setup_project(runner, db_path):
    invoke(runner, db_path, "project", "new", "Export Test", "-d", "Export me")
    invoke(runner, db_path, "sprint", "new", "1", "S1", "-g", "Goal")
    invoke(runner, db_path, "task", "add", "1", "Task Alpha", "-p", "high", "-e", "2.0", "-s", "1")
    invoke(runner, db_path, "task", "add", "1", "Task Beta", "-p", "medium")
    invoke(runner, db_path, "task", "done", "1")
    invoke(runner, db_path, "task", "log", "1", "1.5", "-n", "first pass")


# export markdown ──────────────────────────────────────────────────────────────

def test_export_markdown_stdout(runner, db_path):
    _setup_project(runner, db_path)
    result = invoke(runner, db_path, "export", "markdown", "1", "--stdout")
    assert result.exit_code == 0
    assert "# Export Test" in result.output
    assert "Task Alpha" in result.output
    assert "Task Beta" in result.output


def test_export_markdown_to_file(runner, db_path, tmp_path):
    _setup_project(runner, db_path)
    out = str(tmp_path / "project.md")
    result = invoke(runner, db_path, "export", "markdown", "1", "-o", out)
    assert result.exit_code == 0
    assert "Exported" in result.output
    content = Path(out).read_text()
    assert "Export Test" in content
    assert "first pass" in content


def test_export_markdown_default_filename(runner, db_path, tmp_path):
    """Without -o, should write to <slug>.md in the CWD."""
    _setup_project(runner, db_path)
    with runner.isolated_filesystem():
        result = runner.invoke(
            cli, ["--db", db_path, "export", "markdown", "1"], catch_exceptions=False
        )
    assert result.exit_code == 0
    assert "export-test.md" in result.output


def test_export_markdown_missing_project(runner, db_path):
    result = invoke(runner, db_path, "export", "markdown", "999")
    assert result.exit_code == 1


# export csv ───────────────────────────────────────────────────────────────────

def test_export_csv_tasks_stdout(runner, db_path):
    _setup_project(runner, db_path)
    result = invoke(runner, db_path, "export", "csv", "1", "--stdout")
    assert result.exit_code == 0
    assert "Task Alpha" in result.output
    assert "Task Beta" in result.output
    assert "title" in result.output  # CSV header


def test_export_csv_timelog_stdout(runner, db_path):
    _setup_project(runner, db_path)
    result = invoke(runner, db_path, "export", "csv", "1", "--type", "timelog", "--stdout")
    assert result.exit_code == 0
    assert "first pass" in result.output
    assert "hours" in result.output  # header


def test_export_csv_to_file(runner, db_path, tmp_path):
    _setup_project(runner, db_path)
    out = str(tmp_path / "tasks.csv")
    result = invoke(runner, db_path, "export", "csv", "1", "-o", out)
    assert result.exit_code == 0
    content = Path(out).read_text()
    reader = csv.DictReader(io.StringIO(content))
    rows = list(reader)
    assert len(rows) == 2
    titles = {r["title"] for r in rows}
    assert titles == {"Task Alpha", "Task Beta"}


def test_export_csv_missing_project(runner, db_path):
    result = invoke(runner, db_path, "export", "csv", "999")
    assert result.exit_code == 1
